# Generated by Django 5.2.5 on 2026-02-14 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=254)),
                ('kit_type', models.CharField(choices=[('STANDARD', 'Standard'), ('MINI', 'Mini')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_subscription_date', models.DateField()),
                ('next_subscription_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_notify', models.BooleanField(default=True, help_text='Send automatic due date notifications')),
            ],
            options={
                'ordering': ['next_subscription_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=254)),
                ('kit_type', models.CharField(choices=[('STANDARD', 'Standard'), ('MINI', 'Mini')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('installation_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-installation_date'],
            },
        ),
    ]
