# Generated by Django 5.2.5 on 2026-02-14 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesubscriber',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Formats: (078) 776-8637, 078-776-8637, or 0787768637', regex='^\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='installationclient',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Formats: (078) 776-8637, 078-776-8637, or 0787768637', regex='^\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
    ]
