# Generated by Django 5.2.5 on 2026-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_activesubscriber_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationclient',
            name='kit_type',
        ),
        migrations.AddField(
            model_name='installationclient',
            name='installation_type',
            field=models.CharField(choices=[('STARLINK', 'Starlink Installation'), ('CCTV', 'CCTV Installation'), ('NETWORKING', 'Networking Installation'), ('SOLAR', 'Solar Installation')], default='STARLINK', max_length=20),
        ),
    ]
