# Generated by Django 5.2.5 on 2026-02-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_installationclient_kit_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesubscriber',
            options={'ordering': ['-is_deactivated', 'next_subscription_date']},
        ),
        migrations.AddField(
            model_name='activesubscriber',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activesubscriber',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for deactivation', null=True),
        ),
        migrations.AddField(
            model_name='activesubscriber',
            name='is_deactivated',
            field=models.BooleanField(default=False, help_text='Whether the subscriber account is deactivated'),
        ),
    ]
